# Generated by Django 5.0.2 on 2024-02-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
